"""Initial revision

Revision ID: 507662335e4c
Revises: 
Create Date: 2025-07-18 20:59:05.040615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '507662335e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('documents', 'document_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('documents', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'documents', ['document_name'])
    op.add_column('elements', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('elements', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('elements', 'element_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('elements', 'certificate_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('elements', 'manufacturer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('elements', 'passport_number',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('elements', 'factory_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('elements', 'date_last_metrological_control',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('elements', 'check_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('elements', 'range_measurements',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('elements', 'date_last_check',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('elements', 'block_key_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('elements', 'working_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('elements', 'checking_date_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('elements', 'checking_date_finish',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('elements', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'elements', ['passport_number'])
    op.create_unique_constraint(None, 'elements', ['certificate_number'])
    op.add_column('stations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('stations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('stations', 'station_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'stations', ['station_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', type_='unique')
    op.alter_column('stations', 'station_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('stations', 'updated_at')
    op.drop_column('stations', 'created_at')
    op.drop_constraint(None, 'elements', type_='unique')
    op.drop_constraint(None, 'elements', type_='unique')
    op.alter_column('elements', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'checking_date_finish',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elements', 'checking_date_start',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elements', 'working_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('elements', 'block_key_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('elements', 'date_last_check',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('elements', 'range_measurements',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('elements', 'check_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'date_last_metrological_control',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elements', 'factory_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'passport_number',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('elements', 'manufacturer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('elements', 'certificate_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('elements', 'element_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('elements', 'updated_at')
    op.drop_column('elements', 'created_at')
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'document_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###
